version: "3"
services:
  web:
    image: myhub4/myrepo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

